labdict = {'loss':r'Loss',
           'gradx_loss_2norm': r'$\Vert \nabla_x \ell \Vert$',
           'grady_loss_2norm': r'$\Vert \nabla_y \ell \Vert$',
           'grady_top5_loss_2norm': r'$\Vert \nabla_y \ell_\mathrm{top5} \Vert$',
           'grady_top1_loss_2norm': r'$-\log f_1$',
           'gradw_loss_2norm': r'$\Vert \nabla_w \ell \Vert$',
           'gradx_modelsq_2norm': r'$\Vert \nabla_x \vert f \vert^2 \Vert$',
           'log_pdiff': r'$-\log(f_1-f_2)$',
           'model_entropy': 'Model Entropy',
           'norm_dropout_var': 'Dropout Variance',
           'norm_dropout_0.01_var': 'Dropout Variance (p=0.01)',
           'norm_dropout_0.05_var': 'Dropout Variance (p=0.05)',
           'norm_dropout_0.002_var': 'Dropout Variance (p=0.002)',
           'log_p5diff': r'$-\log(f_1-f_5)$',
           'neg_log_pmax': r'$-\log(f_1)$',
           'gradw_modelsq_2norm': r'$\Vert \nabla_w \vert f \vert^2 \Vert$'}
